### ISSUE TITLE
Feature: allow running some hooks ONLY on pre-commit-ci

### ISSUE THREAD

**Issue by Guts** [pre-commit-ci/issues#100]
Perhaps this ticket would be more appropriate on pre-commit rather than on the CI counterpart. Still, I put it here and don't hesitate in moving it if needed.

Currently, pre-commit.ci allows to skip hooks but the idea would be to be able to specify hooks to be executed **only** on pre-commit.ci but not locally (at least by default).

Use case? I have a heterogeneous team and some hooks require prerequisites (nodejs...) that contributors don't want/need/can't install locally. pre-commit.ci is the ideal response to this situation.

Something like that:

```yaml
ci:
    only: [markdownlint]
    skip: [pylint]

repos:
  - repo: local
    hooks:
    -   id: pylint
        # ...

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
        # ...
```

Or, introducing the notion of context directly into pre-commit:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        context: all
      - id: check-yaml
        context: all

  - repo: local
    hooks:
    -   id: pylint
        context: local
        # ...

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
        context: ci
        # ...
```
