### ISSUE TITLE
Autofix not commiting to branch

### ISSUE THREAD

**Issue by npitsillos** [pre-commit-ci/issues#101]
Hello and thank you for such an amazing tool!  Recently I have witness some strange behaviour where when a check fails and files are changed pre-commit does not update the files automatically.  Here is an example of my yaml file
```
repos:
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
```
Here you can see how the check has failed.
![image](https://user-images.githubusercontent.com/9141826/144640990-abb7a27f-6d32-4ae4-a3d3-84620ad85c30.png)

Here is the pre-commit output.
![image](https://user-images.githubusercontent.com/9141826/144641059-cbaff855-914a-4e41-8132-2889ca63ebbe.png)

Before I changed some github actions this was working fine but as soon as I removed some actions this started to break.  How would I go about resolving this?
