### ISSUE TITLE
Running GitHub Actions only after pre-commit.ci suceeds to save resources, built time etc.

### ISSUE THREAD

**Issue by lorenzwalthert** [pre-commit-ci/issues#106]
## My ideal workflow
* git push triggers pre-commit.ci
* pre-commit.ci may fail, then succeed with auto-fixes, push back to GitHub.
* the suceeded pre-commit ci run triggers all my other GitHub Actions.

## The problem

By default, all GitHub Actions and app integrations are triggered simultaneously. If pre-commit fails on first attempt, then auto-fixes and pushes, all GitHub actions are triggered twice, which is a problem from multiple perspectives:

* If every PR is autofixed, the GitHub Action costs for a user can increase up to 100% in the worst case.
* Since the number of concurrent jobs is limited, the *time to all checks green* doubles in worst case.
* ran at scale, the redundant GitHub Action workflows also have an environmental effect.

If I get the numbers right,  pre-commit.ci ran [over 280k times](https://twitter.com/pre_commit_ci/status/1462188310017851395) as of Nov 2021, and is probably growing exponentially, so I think it's worth having a look at this.

## The solution
I searched the web and found out that it may be possible to trigger a GitHub Action workflow only conditionally on the result of `check_suite`, e.g. as demonstrated [in a repo that previously implemented that functionality](https://github.com/cirrus-actions/check-suite) and now leverages the native GitHub solution:
```yaml
on:
  check_suite:
    type: ['completed']
    
name: Continue after Cirrus CI Complets Successfully
jobs:
  continue:
    name: After Cirrus CI
    if: github.event.check_suite.app.name == 'Cirrus CI' &&  github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Continue	
      run: echo "Hello after Cirrus CI Completed"
```

This is very similar to the [official docs](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#check_suite) and what people discussed on [Github Community Forum](https://github.community/t/conditional-jobs-and-workflows/16296).

However, I could not make pre-commit.ci trigger another workflow in my [example repo](https://github.com/lorenzwalthert/pre-commit.ci-test/blob/master/.github/workflows/R-CMD-check.yaml#L11), maybe the GitHub App (in that case pre-commit.ci) must [use the GitHub API](https://stackoverflow.com/questions/59595803/how-to-trigger-github-workflow-after-a-check-suite-finishes) to set the status of the suite as completed. I don't know what exactly it would take to implement and if it requires further work on the pre-commit.ci side. 
Even if not, I think providing hints in the docs on how to set up GitHub Actions to run *after* pre-commit.ci successfully completes sounds like a useful thing for me to avoid redundant builds.

**Comment by asottile** [comment]
pre-commit.ci doesn't use check suites -- but you can probably do the same with the `status` action trigger: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#status

**Comment by asottile** [comment]
also github I believe cancels in-flight actions in the case of a push -- or at least can be configured to do so -- so the impact of this is rather minimal

**Comment by asottile** [comment]
also this isn't any more actions execution than previously -- previously the linting would fail and a user would push manually still triggering all of CI twice

**Comment by asottile** [comment]
so in conclusion:
-  I don't think there's anything to fix here -- **it's not worse than the status quo** without pre-commit.ci
- you can configure your other CI to fast-fail in the case of pushes (for example [this is how github actions enables this](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run))
- if you need custom post-pre-commit.ci behaviour you can leverage the `status` webhook above

but thanks for the issue nonetheless!

**Comment by lorenzwalthert** [comment]
Thanks for the links, I think the in-flight cancel indeed [got officially supported recently](https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/). This requires opt-in, and I think few people will do that.

> I don't think there's anything to fix here -- it's not worse than the status quo without pre-commit.ci

Well, assuming all checks that pre-commit does happen in CI before, which I think is not the case (at least some of them did not happen). Anyways, we could also see it as an opportunity to improve status quo 😄.

> if you need custom post-pre-commit.ci behaviour you can leverage the status webhook above

Ok, that sounds complicated, I think the cancel on push will suffice.

Anyways, thanks for the answers, appreciate it. Still did not give up the hope that this will be revisited at some point in the future 😉

**Comment by adnathanail** [comment]
Managed to put something together with the status webhook, by having an action that applies a label to a PR when the pre-commit passes, and then adding an `on: pull_request` trigger to my CI workflow

```yaml
on:
  status:

jobs:
  trigger-ci:
    # If the status is from pre-commit.ci and the commit passed (except on master)
    if: github.event.sender.login == 'pre-commit-ci[bot]' && github.event.state == 'success' && github.event.branches[0].name != 'master'

    name: Trigger CI on pre-commit success
    runs-on: ubuntu-latest

    steps:
      - name: (Re-)add label to PR triggering CI run
        env:
          GH_TOKEN: ${{ secrets.PR_LABEL_TOKEN }}
        run: |
          # Get PR details
          PR_INFO=$(gh pr list --repo YOUR_ORG/YOUR_REPO --head "${{ github.event.branches[0].name }}" --json number -q '.[0]')
          PR_NUMBER=$(echo "$PR_INFO" | jq -r '.number')

          # Remove label if it exists (ignore errors if it doesn't)
          gh pr edit "$PR_NUMBER" --repo YOUR_ORG/YOUR_REPO --remove-label "pre-commit.ci passed" | true
          # Add label again
          gh pr edit "$PR_NUMBER" --repo YOUR_ORG/YOUR_REPO --add-label "pre-commit.ci passed"
```

You will need to:
- Manually create the `pre-commit.ci passed` label
- Create a personal access token with `repo`, `read:org`, and `read:project` scopes, and set it as a repository secret called `PR_LABEL_TOKEN`
- Create a `ci.yml` (or change `ci.yml` above, to whatever your action you want to run is)

Then in your CI actions file add

```yaml
# Run on push to master or when label applied (see if on build)
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [labeled]
```
(The `push` on `master` is optional)

And on the job

```yaml
jobs:
  build:
    ...
    # Run on push (to master) or when the pre-commit.ci passed label is added by the pre-commit-ci-trigger-build.yml
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'pre-commit.ci passed')
    ...
```

(Again remove the `push` if you want)
