### ISSUE TITLE
Executable `xxx` not found

### ISSUE THREAD

**Issue by PointKernel** [pre-commit-ci/issues#108]
I'm setting up my first `pre-commit.ci` so apologies if I missed something obvious. To perform auto-formatting via `clang-format`, I got the error below:
```bash
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

Executable `clang-format` not found
```
Here is my configuration file:
```yaml
repos:
      - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v11.1.0
        hooks:
              - id: clang-format
                name: clang-format
                description: Format files with ClangFormat.
                entry: clang-format
                language: system
                files: \.(cu|cuh|h|hpp|cpp|inl)$
                'types_or': [file]
                args: ['-fallback-style=none', '-style=file', '-i']

default_language_version:
      python: python3
``` 
Not sure it's a problem of `mirrors-clang-format` or `pre-commit.ci`. More details can be found at https://github.com/PointKernel/toto-cuda/pull/1/.

Any ideas on how to fix this issue? Thanks!
