### ISSUE TITLE
Show version info for additional_dependencies in build step

### ISSUE THREAD

**Issue by janosh** [pre-commit-ci/issues#113]
E.g. for

```yml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-pyyaml]
```

list what versions of `types-requests`, `types-pyyaml` were installed.
