### ISSUE TITLE
Skipped hook triggers “clone of ... exceeds tier max size”

### ISSUE THREAD

**Issue by adamchainz** [pre-commit-ci/issues#150]
With `.pre-commit-config.yaml`:

```yaml
repos:
- repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.66.1
    hooks:
      - id: cfn-python-lint
        files: '^files/cloudformation/.*\.yml$'
ci:
  skip:
    - cfn-python-lint
```

pre-commit.ci’s build step stops with the error:

```
clone of https://github.com/aws-cloudformation/cfn-lint@v0.66.1 exceeds tier max size 100MiB: 142.1MiB
```

This is sad, because the hook is skipped so shouldn't need cloning.

(Issue filed with the repo: https://github.com/aws-cloudformation/cfn-lint/issues/2455.)
