### ISSUE TITLE
perl hook environment fails to build

### ISSUE THREAD

**Issue by hdadhich01** [pre-commit-ci/issues#153]
[latexindent.pl](https://github.com/cmhughes/latexindent.pl) fails to build [here](https://results.pre-commit.ci/run/github/581340614/1671757573.gyGfc9S_T6-jDT4FC4LCMg).
```yaml
- repo: https://github.com/cmhughes/latexindent.pl
  rev: V3.19.1
  hooks:
  - id: latexindent
```
something to do with perl and how the ci server sets up hooks using it for their env
