### ISSUE TITLE
`pre-commit-ci/lite-action` isn't pushing changes

### ISSUE THREAD

**Issue by deepyaman** [pre-commit-ci/issues#156]
Hi,

I'm trying the lite Action on a private repo.

It is creating an artifact:

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/14007150/210601874-07896567-7331-4cd6-ac05-2a0212c83535.png">

The `data.json` contents look reasonable at a glance:

```json
{"action_version":"v1.0.0","msg":"[pre-commit.ci lite] apply automatic fixes","base_tree":"64ce8fb13af0a2f133ae5053be3112659c41659b","delete":[],"binary":[],"text":[["firewood/firewood/cli/__init__.py","100644","\"\"\"The CLI module describes tools used to build the CLI for Firewood.\"\"\"\n__all__ = [\n    \"app\",\n]\n\nfrom .cli import app\n"]]}
```

I've added the follow tasks to my workflow:

```yaml
       - uses: pre-commit/action@v3.0.0

       - uses: pre-commit-ci/lite-action@v1.0.0
         if: always()
```

I've also tried it withough `pre-commit/action` (should it still be used, since it's been deprecated for a while?), but it also didn't work:

```yaml
       # code quality check
       - name: Run pre-commit on all files
         run: pre-commit run --all-files

       - uses: pre-commit-ci/lite-action@v1.0.0
         if: always()
```

Last but not least, I did make sure to install the GitHub Application for my repo, as instructed.

Any idea what's going wrong here?
