### ISSUE TITLE
python3 exceeds tier max size 

### ISSUE THREAD

**Issue by winterz** [pre-commit-ci/issues#171]
https://results.pre-commit.ci/run/github/180151401/1676027392.bBbYCsLrRJuA86IX-IvV1g

shows the error "build of https://github.com/PyCQA/pylint:PySide2,PySide6@v2.15.5 for python@python3 exceeds tier max size 250MiB: 937.8MiB"

is there a way to increase the default max tier size in my .pre-commit-config.py somehow?
or other suggestions on how to get past this limitation would be greatly appreciated.

**Comment by winterz** [comment]
here's the relevant stanza from my .pre-commit-config.py
```
- repo: https://github.com/PyCQA/pylint
  rev: v2.15.5
  hooks:
  - id: pylint
    exclude: ^(.cmake-format.py|conan/conanfile.py)
    additional_dependencies: ["PySide2", "PySide6"]
```
