### ISSUE TITLE
[feature] Can autoupdate_branch be an array?

### ISSUE THREAD

**Issue by Freed-Wu** [pre-commit-ci/issues#178]
<https://pre-commit.ci/#configuration> said autoupdate_branch is a string of branch name. Can it be an array, such as:

```yaml
ci:
  autoupdate_branch:
    - main
    - old-version
```
