### ISSUE TITLE
Unexpected hook in skip block using alias

### ISSUE THREAD

**Issue by blarghmatey** [pre-commit-ci/issues#186]
I am trying to disable a specific hook configuration that is duplicating another ID that I would also like to run in CI. When I set an alias on the second configuration and add that alias to the `ci:skip` list I get the error message:
```
==> File .pre-commit-config.yaml
==> At Config()
==> At key: ci
==> At key: skip
=====> unexpected hook ids: prettier-django
```

The configuration in question looks like:
```yaml
ci:
  skip:
    - prettier-django
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, scss, sass, css]
        args:
          - --no-config
          - --no-semi
      - id: prettier
        alias: prettier-django
        name: prettier-django
        types: [html]
        additional_dependencies:
          - prettier
          - prettier-plugin-django-alpine
```
