### ISSUE TITLE
NameResolutionError for pypi.org

### ISSUE THREAD

**Issue by chemelli74** [pre-commit-ci/issues#189]
I get a consistent failed message:

`HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/pytest-cov/4.1.0/json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fefe90da4d0>: Failed to resolve 'pypi.org' ([Errno -3] Temporary failure in name resolution)"))`

Is it a known issue ?

Simone

**Comment by asottile** [comment]
pre-commit ci does not allow network at runtime.  please in the future search the issue tracker as there are duplicates. also this is github not email so no need to add a signature to your messages

**Comment by chemelli74** [comment]
> pre-commit ci does not allow network at runtime. please in the future search the issue tracker as there are duplicates. 

Do you mind pointing me to the correct configuration then ? I just added the "ci" section to my pre-commit in order to get autoupdates.

Repo cfg: https://github.com/chemelli74/aiovodafone/blob/main/.pre-commit-config.yaml#L6-L9

> also this is github not email so no need to add a signature to your messages

I don't see a signature, but if you are reffering to my name in the end, I just think it's polite.

Simone

**Comment by chemelli74** [comment]
For future reference, old config:

```yaml
- repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
```
new config:

```yaml
- repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        args: ["--lock"]
```
