### ISSUE TITLE
Pre-commit ci says not a PR

### ISSUE THREAD

**Issue by thesujai** [pre-commit-ci/issues#209]
hey @asottile 
I was trying to run the pre-commit-ci lite if there is a comment /autofixme! in my PR. But the pre-commit ci skips saying not a PR.
Here is the code:
```
name: Pre-commit CI
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issue_comment:
    types: [created]

jobs:
  main:
    name: "Pre-commit checks"
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/autofixme!'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.0.2
        if: always()



```
Is there a way to fix this? Maybe it is getting triggered on event `issue_comment` but is there a way i can override this?
