### ISSUE TITLE
Feature: make autoupdate PR description configurable

### ISSUE THREAD

**Issue by VannTen** [pre-commit-ci/issues#213]
Is adding the possibility to customize the PR description of the autoupdater a feature you would acc
ept ?
Something like:
```yaml
ci:
  autoupdate_pr_description_footer: |
        My custom PR desc footer
```

Thanks a lot.
