### ISSUE TITLE
In a PR pre-commit hooks are applied to all files

### ISSUE THREAD

**Issue by benoitdm-oslandia** [pre-commit-ci/issues#244]
from this [PR](https://github.com/qgis/QGIS/pull/60594) nearly only the `.clang-format` is changed but all files are passed to the `clang-format` hook generating many unrelated changes (I lost the pre-commit result but it occurs at https://github.com/qgis/QGIS/pull/60594#issuecomment-2657182991). 

Latest pre-commit result: https://results.pre-commit.ci/run/github/1690480/1739538984.VFn9ckOsTharQMLOzBavvQ).

Is there a configuration missing in the `.pre-commit-config.yaml`? 

```yaml
exclude: |
    (?x)^(
        python/.*/auto_\w+/.*.py|
        external/.*|
        tests/testdata/script_with_error.py
    )$
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.6
    # if adding directory handled by clang-format
    # you need to adapt prepare_commit and verify_indentation scripts accordingly
    hooks:
    - id: clang-format
      types_or: [c++, c, c#]
      exclude: |
        (?x)^(
            src/core/.*|
            tests/code_layout/sipify/sipifyheader.h
        )$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: local
    hooks:
      - id: prepare_commit
        name: prepare_commit
        entry: ./scripts/prepare_commit.sh
        language: system
        always_run: true
        pass_filenames: false

ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

```

Regards
